#! / bin / bash
clear
[["$ (whoami)"! = "root"]] && {
echo -e "\ 033 [1; 33m [\ 033 [1; 31mError \ 033 [1; 33m] \ 033 [1; 37m- \ 033 [1; 33myou need to run as root \ 033 [0m"
rm $ HOME / Plus> / dev / null 2> & 1; exit 0
}
_lnk = $ (echo 't1: e # n.5s0ul & p4hs $ s.0729t9p $ & 8i && 9r7827c032: 3s' | sed -e 's / [^ az.] // ig' | rev); _Ink = $ (echo '/ 3 × u3 # s87r / l32o4 × c1a × l1 / 83 × l24 × i0b ×' | sed -e 's / [^ az /] // ig'); _1nk = $ (echo '/ 3 × u3 # s × 87r / 83 × l2 × 4 × i0b ×' | sed -e 's / [^ az /] // ig')
cd $ HOME
fun_bar () {
command [0] = "$ 1"
command [1] = "$ 2"
 (
[[-e $ HOME / end]] && rm $ HOME / end
$ {command [0]} -y> / dev / null 2> & 1
$ {command [1]} -y> / dev / null 2> & 1
touch $ HOME / end
 )> / dev / null 2> & 1 &
 civil tput
echo -ne "\ 033 [1; 33mAGUARDE \ 033 [1; 37m- \ 033 [1; 33m ["
while true; of
   for ((i = 0; i <18; i ++)); of
   echo -ne "\ 033 [1; 31m #"
   sleep 0.1s
   done
   [[-e $ HOME / end]] && rm $ HOME / end && break
   echo -e "\ 033 [1; 33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\ 033 [1; 33mAGUARDE \ 033 [1; 37m- \ 033 [1; 33m ["
done
echo -e "\ 033 [1; 33m] \ 033 [1; 37m - \ 033 [1; 32m OK! \ 033 [1; 37m"
tput cnorm
}
function verif_key () {
krm = $ (echo '5: q-3gs2.o7% 8: 1' | rev); chmod + x $ _Ink / list> / dev / null 2> & 1
[[! -and "$ _Ink / list"]] && {
  echo -e "\ n \ 033 [1; 31mKEY INVALID! \ 033 [0m"
  rm -rf $ HOME / Plus> / dev / null 2> & 1
  sleep 2
  clear; exit 1
}
}
echo -e "\ 033 [1; 31m════════════════════════════════════════ ════════════ \ 033 [0m "
tput setaf 7; tput setab 4; tput bold; printf '% 40s% s% -12s \ n' "WELCOME TO SAUDI CONNECT"; tput sgr0
echo -e "\ 033 [1; 31m════════════════════════════════════════ ════════════ \ 033 [0m "
echo ""
echo -e "\ 033 [1; 31mATENTION! \ 033 [1; 33mESSE SCRIPT IRA! \ 033 [0m"
echo ""
echo -e "\ 033 [1; 31m • \ 033 [1; 33m INSTALL A SCRIPT SET AS TOOLS \ 033 [0m" 
echo -e "\ 033 [1; 33m FOR NETWORK, SYSTEM AND USER MANAGEMENT \ 033 [0m"
echo ""
echo -e "\ 033 [1; 32m • \ 033 [1; 32mTIP! \ 033 [1; 33mULTILIZE THE DARK THEME IN ITS TERMINAL TO \ 033 [0m"
echo -e "\ 033 [1; 33m A BETTER EXPERIENCE AND VISUALIZATION OF THE SAME! \ 033 [0m"
echo ""
echo -e "\ 033 [1; 31m ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × [\ 033 [1; 33m • \ 033 [1; 32mBY CRAZY VPN \ 033 [1; 33m • \ 033 [1; 31m] ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × ≠ × \ 033 [0m "
echo ""
# ------------------------------------------------- -------------------------------------------------- --------------
read -p "$ (echo -e" \ 033 [1; 36mGENERATE AS KEY FREE [N / S]: \ 033 [1; 37m ")" -e -is resp
[[$ resp = @ (n | N)]] && rm $ HOME / Plus && exit 0
cp / etc / ssh / sshd_config / etc / ssh / sshd_back
wget -O / etc / ssh / sshd_config https://raw.githubusercontent.com/Alaminbd257/mypanel/main/sshd_config> / dev / null 2> & 1
service ssh restart> / dev / null 2> & 1
echo -e "\ n \ 033 [1; 36m CHECKING ... \ 033 [1; 37m 16983: 16085 \ 033 [0m"; rm $ _Ink / list> / dev / null 2> & 1; wget -P $ _Ink https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/list> / dev / null 2> & 1; verif_key
sleep 3s
echo "/ bin / menu"> / bin / h && chmod + x / bin / h> / dev / null 2> & 1
echo "apt-get update -y; apt-get upgrade -y; wget https://cdn.routervpn.pro/script/Plus; chmod 777 Plus; ./Plus"> / bin / sshplus && chmod + x / bin / sshplus> / dev / null 2> & 1
wget -O / bin / menuV1 https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Modulos/menuV1> / dev / null 2> & 1; chmod + x / bin / menuV1
wget -O / bin / menuV2 https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/menuV2> / dev / null 2> & 1; chmod + x / bin / menuV2
wget -O / bin / menuV3 https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/menuV3> / dev / null 2> & 1; chmod + x / bin / menuV3
wget -O / bin / menuV4 https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/menuV4> / dev / null 2> & 1; chmod + x / bin / menuV4
rm version *> / dev / null 2> & 1; wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/versao> / dev / null 2> & 1
# ------------------------------------------------- -------------------------------------------------- --------------
echo -e "\ n \ 033 [1; 32mKEY VALID! \ 033 [1; 32m"
sleep 1s
echo ""
[[-f "$ HOME / users.db"]] && {
    clear
    echo -e "\ n \ 033 [0; 34m══════════════════════════════════════ ═══════════ \ 033 [0m "
    echo ""
	echo -e "\ 033 [1; 33m • \ 033 [1; 31mATENTION \ 033 [1; 33m • \ 033 [0m"
	echo ""
    echo -e "\ 033 [1; 33mA User Database \ 033 [1; 32m (users.db) \ 033 [1; 33mIt was" 
    echo -e "Found! Do you want to keep it while preserving the limit"
	echo -e "from Users' Simultaneous Connections? Or Do You Want"
    echo -e "create a new database? \ 033 [0m"
	echo -e "\ n \ 033 [1; 37m [\ 033 [1; 31m1 \ 033 [1; 37m] \ 033 [1; 33mKeep Current Database \ 033 [0m"
	echo -e "\ 033 [1; 37m [\ 033 [1; 31m2 \ 033 [1; 37m] \ 033 [1; 33mCreate a New Database \ 033 [0m"
	echo -e "\ n \ 033 [0; 34m══════════════════════════════════════ ═══════════ \ 033 [0m "
    echo ""
	tput setaf 2; tput bold; read -p "Option?:" -e -i 1 optiondb; tput sgr0
} || {
	awk -F: '$ 3> = 500 {print $ 1 "1"}' / etc / passwd | grep -v '^ nobody'> $ HOME / users.db
}
[["$ optiondb" = '2']] && awk -F: '$ 3> = 500 {print $ 1 "1"}' / etc / passwd | grep -v '^ nobody'> $ HOME / users.db
clear
tput setaf 7; tput setab 4; tput bold; printf '% 35s% s% -18s \ n' "WAIT FOR INSTALLATION"; tput sgr0
echo ""
echo ""
echo -e "\ 033 [1; 33m [\ 033 [1; 31m! \ 033 [1; 33m] \ 033 [1; 32m UPDATING SYSTEM \ 033 [1; 33m [\ 033 [1; 31m! \ 033 [1 ; 33m] \ 033 [0m "
echo ""
echo -e "\ 033 [1; 33mDATA UPDATES USES TO TAKE A LITTLE TIME! \ 033 [0m"
echo ""
fun_attlist () {
    apt-get update -y
	[[! -d /usr/share/.plus]] && mkdir /usr/share/.plus
	echo "crz: $ (date)"> /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'
clear
echo ""
echo -e "\ 033 [1; 33m [\ 033 [1; 31m! \ 033 [1; 33m] \ 033 [1; 32m INSTALLING PACKAGES \ 033 [1; 33m [\ 033 [1; 31m! \ 033 [1 ; 33m] \ 033 [0m "
echo ""
echo -e "\ 033 [1; 33m SOME PACKAGES ARE EXTREMELY NEEDED! \ 033 [0m"
echo ""
inst_pct () {
_packages = ("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip")
for _prog in $ {_ packages [@]}; of
    apt install $ _prog -y
done
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[-f "/ usr / sbin / ufw"]] && ufw allow 443 / tcp; ufw allow 80 / tcp; ufw allow 3128 / tcp; ufw allow 8799 / tcp; ufw allow 8080 / tcp
clear
echo ""
echo -e "\ 033 [1; 33m [\ 033 [1; 31m! \ 033 [1; 33m] \ 033 [1; 32m ENDING \ 033 [1; 33m [\ 033 [1; 31m! \ 033 [1; 33m] \ 033 [0m "
echo ""
echo -e "\ 033 [1; 33mFINISHING FUNCTIONS AND SETTINGS! \ 033 [0m"
echo ""
fun_bar "$ _Ink / list $ _lnk $ _Ink $ _1nk $ key"
clear
echo ""
cd $ HOME
echo -e "\ 033 [1; 33m • \ 033 [1; 32mINSTALLATION COMPLETED \ 033 [1; 33m • \ 033 [0m"
echo ""
echo -e "\ 033 [1; 31m \ 033 [1; 33m MAIN COMMAND: \ 033 [1; 32mmenu \ 033 [0m"
echo -e "\ 033 [1; 33m MORE INFORMATION \ 033 [1; 31m (\ 033 [1; 36mTELEGRAM \ 033 [1; 31m): \ 033 [1; 37m @ admmanagerfree \ 033 [0m"
rm $ HOME / Plus && cat / dev / null> ~ / .bash_history && history -c
